const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const src=fs.readFileSync(require('node:path').join(__dirname,'../app.js'),'utf8');
const cost=src.slice(src.indexOf('function setOrderCostFieldForProduct'),src.indexOf('\nfunction clearQuickProductButton'));
function setup(role='admin',type='SALES_SELF_ORDER'){
 const elements={orderCostPrice:{value:'',dataset:{}},orderCostFieldWrap:{style:{},querySelector:()=>({})},orderProcurementType:{value:type}};
 const x=vm.createContext({window:{},currentUserRole:role,orderModalOpenGeneration:1,document:{getElementById:id=>elements[id]},loadVisibleProductCost:async()=>role==='sales'?null:12});vm.runInContext(cost,x);return {x,elements};
}
test('authorized self order carries standard cost, including zero',async()=>{const {x,elements}=setup();await x.applyOrderProductCost({productId:'P1'});assert.equal(elements.orderCostPrice.value,'12');x.loadVisibleProductCost=async()=>0;await x.applyOrderProductCost({productId:'P2'});assert.equal(elements.orderCostPrice.value,'0');});
test('manual transaction cost remains unchanged',async()=>{const {x,elements}=setup();elements.orderCostPrice.value='7';await x.applyOrderProductCost({productId:'P1'});assert.equal(elements.orderCostPrice.value,'7');});
test('normal order displays reference cost read-only',async()=>{const {x,elements}=setup('admin','PURCHASING_PO');await x.applyOrderProductCost({productId:'P1'});assert.equal(elements.orderCostPrice.value,'12');assert.equal(elements.orderCostPrice.readOnly,true);});
test('sales does not receive protected standard costs',async()=>{const {x,elements}=setup('sales','PURCHASING_PO');await x.applyOrderProductCost({productId:'P1'});assert.equal(elements.orderCostPrice.value,'');assert.equal(elements.orderCostFieldWrap.style.display,'none');});
test('older product cost cannot overwrite newer selection',async()=>{const {x,elements}=setup();let resolve;x.loadVisibleProductCost=item=>item.productId==='P1'?new Promise(r=>resolve=r):Promise.resolve(8);const first=x.applyOrderProductCost({productId:'P1'});await x.applyOrderProductCost({productId:'P2'});resolve(12);await first;assert.equal(elements.orderCostPrice.value,'8');});
test('late cost read cannot modify next opened order or manual input',async()=>{const {x,elements}=setup();let resolve;x.loadVisibleProductCost=()=>new Promise(r=>resolve=r);const first=x.applyOrderProductCost({productId:'P1'});x.orderModalOpenGeneration++;resolve(12);await first;assert.equal(elements.orderCostPrice.value,'');});
const start=src.indexOf('window.removeInventoryReplenishmentReminder');const reminder=src.slice(start,src.indexOf('\n};',start)+3);
function reminderSetup(authorized=true,confirmed=true){const calls=[],x=vm.createContext({window:{},canManageInventoryStockPolicy:()=>authorized,confirm:()=>confirmed,alert:s=>calls.push(['alert',s]),INVENTORY_STOCK_POLICIES:{ORDER_ONLY:'ORDER_ONLY'},saveInventoryPlanningSettings:async(...a)=>calls.push(['policy',...a]),loadInventoryReplenishmentCenter:async force=>calls.push(['reload',force]),showActionFeedback:s=>calls.push(['feedback',s])});vm.runInContext(reminder,x);return {x,calls};}
test('removing reminder changes planning policy then reloads without deleting stock',async()=>{const {x,calls}=reminderSetup();await x.window.removeInventoryReplenishmentReminder('I1');assert.deepEqual(calls[0],['policy','I1','ORDER_ONLY']);assert.deepEqual(calls[1],['reload',true]);});
test('unauthorized or cancelled reminder removal never writes',async()=>{for(const args of [[false,true],[true,false]]){const {x,calls}=reminderSetup(...args);await x.window.removeInventoryReplenishmentReminder('I1');assert.equal(calls.some(c=>c[0]==='policy'),false);}});
